### ISSUE TITLE
利用できるhandlerがない

### ISSUE THREAD

**Issue by jmfoucher** [ochi51/cybozu-http#60]
cybozu-httpを作って頂きありがとうございました。

フシェと申します。

現在利用してるホスティングサービスでは、allow_url_fopenが無効し、cURLを利用できません。

他のハンドラーを移植・開発したいですが、経験が足りなくて、どの方向へ行った方が良いか、良く分かりません。
カスタム・ハンドラーを作成しても良いかどうか、自分で判断しにくいため、まずはご意見を聞かせて頂きたいと思います。

**Comment by ochi51** [comment]
cybozu-http をご利用いただきありがとうございます！

cybozu-http は cURL が前提のライブラリのため、この部分を入れ替えることを想定していません。
また、独自の handler を追加できるカスタマイズ性がないです。
お時間がないようでしたら、Fork して好きなように開発していただくのがいいかと思います。
お時間があるようでしたら handler を追加できる PR を用意していただけると、レビューの上、マージいたします！
